### ISSUE TITLE
Rasberry Pi 4 js error

### ISSUE THREAD

**Issue by jasondelv** [vervallsweg/cast-web-api-desktop#15]
Attempting install with correct armv7 appimage results in JavaScript error. "A JavaScript error occurred in the main process. Uncaught exception: typeerror: error processing argument at index 0, conversion failure from/tmp/.mount_cast-wu25t0b/resources/app/image/icon/icon-small.png at createTray... attached image of error

![20200628_190349](https://user-images.githubusercontent.com/32424177/85960617-e0f84a00-b972-11ea-8be6-ee33673f64a8.jpg)
 Thank you so much for your assistance. Purchased the pi4 for this function.

**Comment by smithp7117** [comment]
Hi Jasondelv
I am having the same issue. Have you managed to resolve the issue?

**Comment by illgainedgoods** [comment]
I am seeing the same error when attempting to use "cast-web-api-desktop-1.2.1-armv7l.AppImage" on a Raspberry Pi 4+.

Error text: 

> A JavaScript error occurred in the main process
> Uncaught Exception:
> Type Error: Error processing argument at index 0, conversion failure from /tmp/.mount_cast-w78mcRi/resources/app/img/icon/icon-small.png
>   at createTray (/tmp/.mount_cast_w78mcRi/resources/app/main.js:14:12)
>   at App.app.on (/tmp/.mount_cast-w78mcRi/resources/app/main.js:120:5)
>   at App.emit (events.js:187:15)

**Comment by swdeason** [comment]
Did we find a solution to this issue? If so, please share.

Thanks
