### ISSUE TITLE
Error executing cast web api desktop on Ubuntu 19.04

### ISSUE THREAD

**Issue by singhj0910** [vervallsweg/cast-web-api-desktop#5]
Since I wasn't able to get this to work on my RPI 3 I decided to try on my Ubuntu desktop and encountered a different issue now. Upon executing the AppImage I get a javascript popup error as well as this error in the terminal:

 (node:11595) UnhandledPromiseRejectionWarning: Error: Failed to get 'logs' path
    at resolve (/tmp/.mount_cast-wVSi9hg/resources/app/main.js:362:122)
    at new Promise (<anonymous>)
    at getInit (/tmp/.mount_cast-wVSi9hg/resources/app/main.js:361:12)
    at WebContents.mainWindow.webContents.on (/tmp/.mount_cast-wVSi9hg/resources/app/main.js:49:9)
    at WebContents.emit (events.js:182:13)
(node:11595) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11595) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The app does start but it gets stuck at the loading screen and I cannot click on start. Please advise.

**Comment by gpetru1** [comment]
I have this issue as well. What type and version of Linux has this been tested as working on?

**Comment by MrRasmus** [comment]
Is there a solution to this? - Still trying to get it to work on Raspbian - But no luck at all, either with appimage or cast-web-api-cli -g - Just says "Starting" and never get further
